name: Unit Tests

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Runs every week at midnight on Sunday

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.12","3.11","3.10" ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: python -m pip install --upgrade pip

      - name: Install Package in Editable Mode with Development Dependencies
        run: python -m pip install -e ".[pin]"

      - name: Run Tests
        working-directory: ${{ github.workspace }}
        run: pytest -s tests/
